name: Build and Push Docker Image
description: Build and push a Docker image to Nexus

inputs:
  image-version:
    description: 'The version tag for the Docker image'
    required: true
    default: 'latest'
  repository-name:
    description: 'The name of the Nexus repository'
    required: true
    default: 'my-repository'
runs:
  using: "composite"
  steps:
    - name: Login to Nexus
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.NEXUS_REGISTRY }}
        username: ${{ secrets.NEXUS_USERNAME }}
        password: ${{ secrets.NEXUS_PASSWORD }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.NEXUS_REGISTRY }}/${{ inputs.repository-name }}:${{ inputs.image-version }}