name: Publish raw content
description: Publish raw content to Nexus

inputs:
  repository-name:
    description: 'The name of the Nexus repository'
    required: true
    default: 'my-repository'
  file-path:
    description: 'The path to the file to be published'
    required: true
    default: 'path/to/file.txt'

runs:
  using: "composite"
  steps:
    - name: Publish Raw Content to Nexus
      shell: bash
      env:
        NEXUS_REGISTRY: ${{ secrets.NEXUS_REGISTRY }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        REPOSITORY_NAME: ${{ inputs.repository-name }}
        FILE_PATH: ${{ inputs.file-path }}
      run: |
        curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file $FILE_PATH $NEXUS_REGISTRY/repository/$REPOSITORY_NAME/$(basename $FILE_PATH)
